name: Reusable setup for the python environment and the package installation
runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
  - name: Set up Python 3.10
    uses: actions/setup-python@v5
    with:
      python-version: "3.10"
      cache: "pip"
  - name: Install package (and its dependencies)
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install --user .[test]
