name: wheels_cross_64bit
on: [workflow_dispatch]
jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --user --upgrade cibuildwheel
      - run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_MACOS: arm64
          CIBW_SKIP: cp36-* cp37-* pp*
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_MANYLINUX_I686_IMAGE: manylinux_2_28
          CIBW_MANYLINUX_PYPY_X86_64_IMAGE: manylinux_2_28
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28
          CIBW_MANYLINUX_PPC64LE_IMAGE: manylinux_2_28
          CIBW_MANYLINUX_S390X_IMAGE: manylinux_2_28
          CIBW_MANYLINUX_PYPY_AARCH64_IMAGE: manylinux_2_28
          CIBW_MANYLINUX_PYPY_I686_IMAGE: manylinux_2_28
      - uses: actions/upload-artifact@v4
        with:
          name: JAXbind_macos64_cross
          path: ./wheelhouse/*.whl
